name: gamebox
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/organisation_logo.png
    - assets/games.png
    - assets/home_logo.png
    - assets/games_images/tic_tac_toe.png
    - assets/games_images/memory_game.png
    - assets/games_images/brick_breaker.png
    - assets/games_images/catch_the_ball.png
    - assets/games_images/puzzle_game.png
    - assets/games_images/simon_says.png

  # Optionally, if you have fonts to include:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
